### ISSUE TITLE
Utilisation du STT manager 

### ISSUE THREAD

**Issue by YannLuke** [linto-ai/linto-platform-service-manager#5]
Bonjour,

pour l'exécution du STT manager, il est indiqué qu'il faut exécuter le contrôleur ingress : LINTO_STACK_STT_SERVICE_MANAGER_INGRESS_CONTROLLER, puis d'exécuter le stt manager. 

Suffit-il de partir du fichier linto-platform-stt-service-manager-nginx.yml pour créer une stack swarm, et d'y déployer le contrôleur ingress avec le bon paramétrage pour ensuite pouvoir exécuter le stt manager ? 

Cordialement,
Yann.

**Comment by damienlaine** [comment]
http://doc.linto.ai heavily revamped
